run:
	clear && go build -race
	go test ./... -v
	./httptool -parallel 3 http://google.com  http://yahoo.com  facebook.com  twitter.com  yahoo.com

runAll:
	clear && go build -race
	go test ./... -v
	./httptool -parallel 6 http://yahoo.com http://google.com http://facebook.com http://yahoo.com http://yandex.com http://twitter.com http://reddit.com/r/funny http://reddit.com/r/notfunny http://baroquemusiclibrary.com http://yahoo.com http://google.com http://facebook.com http://yahoo.com http://yandex.com http://twitter.com http://reddit.com/r/funny http://reddit.com/r/notfunny http://baroquemusiclibrary.com http://yahoo.com http://google.com http://facebook.com http://yahoo.com http://yandex.com http://twitter.com http://reddit.com/r/funny http://reddit.com/r/notfunny http://baroquemusiclibrary.com http://yahoo.com http://google.com http://facebook.com http://yahoo.com http://yandex.com http://twitter.com http://reddit.com/r/funny http://reddit.com/r/notfunny http://baroquemusiclibrary.com http://yahoo.com http://google.com http://facebook.com http://yahoo.com http://yandex.com http://twitter.com http://reddit.com/r/funny http://reddit.com/r/notfunny http://baroquemusiclibrary.com http://yahoo.com http://google.com http://facebook.com http://yahoo.com http://yandex.com http://twitter.com http://reddit.com/r/funny http://reddit.com/r/notfunny http://baroquemusiclibrary.com http://yahoo.com http://google.com http://facebook.com http://yahoo.com http://yandex.com http://twitter.com http://reddit.com/r/funny http://reddit.com/r/notfunny http://baroquemusiclibrary.com http://yahoo.com http://google.com http://facebook.com http://yahoo.com http://yandex.com http://twitter.com http://reddit.com/r/funny http://reddit.com/r/notfunny http://baroquemusiclibrary.com http://yahoo.com http://google.com http://facebook.com http://yahoo.com http://yandex.com http://twitter.com http://reddit.com/r/funny http://reddit.com/r/notfunny http://baroquemusiclibrary.com http://yahoo.com http://google.com http://facebook.com http://yahoo.com http://yandex.com http://twitter.com http://reddit.com/r/funny http://reddit.com/r/notfunny http://baroquemusiclibrary.com http://yahoo.com http://google.com http://facebook.com http://yahoo.com http://yandex.com http://twitter.com http://reddit.com/r/funny http://reddit.com/r/notfunny http://baroquemusiclibrary.com http://yahoo.com http://google.com http://facebook.com http://yahoo.com http://yandex.com http://twitter.com http://reddit.com/r/funny http://reddit.com/r/notfunny http://baroquemusiclibrary.com

.Phony:
	run
